name: push

on:
  push:
    branches: [ main ]

jobs:
  announcepush:
    runs-on: ubuntu-latest
    steps:
      - name: Get repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Send push to Discord
        run: |
          curl -i -H "Accept: application/json" -H "Content-Type: application/json" -X POST --data \
          "{\"username\": \"Github\", \"avatar_url\": \"${{ secrets.AVATARURL }}\", \"content\": \"\
          :white_check_mark: New commit pushed to [*$GITHUB_REPOSITORY*]($GITHUB_SERVER_URL/$GITHUB_REPOSITORY) by [*$GITHUB_ACTOR*]($GITHUB_SERVER_URL/$GITHUB_ACTOR) - \
          [Click me]($GITHUB_SERVER_URL/$GITHUB_REPOSITORY/commit/$GITHUB_SHA)\n\
          :loudspeaker: Title: *$(git show -s --format=%s)*\"}" ${{ secrets.WEBHOOKURL }}
