name: push

on:
  push:
    branches: [ main ]

jobs:
  announcepush:
    runs-on: ubuntu-latest
    steps:
      - name: Get repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: kceb/pull-request-url-action@v1
        id: pr-url
      - run: echo "${{ steps.pr-url.outputs.url }}"
